services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  CPSIT\ImportExportCore\:
    resource: '../Classes/*'

  CPSIT\ImportExportCore\Messaging\MessageContainer:
    public: true
  #CPSIT\ImportExportCore\Messaging\MessageContainerInterface: '@ImportExportCore\Messaging\MessageContainer'
